# Generated by Django 2.1.5 on 2021-04-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productitem',
            name='description',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='productitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
