# Generated by Django 2.1.5 on 2021-04-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210404_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='imageUrl',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='productitem',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productitem',
            name='productId',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='productitem',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='productitem',
            name='shareLink',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='description',
            field=models.TextField(default='', max_length=512),
        ),
    ]
