# Generated by Django 2.1.5 on 2021-04-06 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210407_0218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productitem',
            name='ids',
        ),
    ]
