# Generated by Django 2.1.5 on 2021-04-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_productitem_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productitem',
            name='imageUrl',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='productId',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='shareLink',
        ),
        migrations.AlterField(
            model_name='productitem',
            name='name',
            field=models.CharField(max_length=96),
        ),
    ]
